export const ADD_CART_ITEM = "ADD_CART_ITEM"
export const REMOVE_CART_ITEM = "REMOVE_CART_ITEM"
export const EMPTY_CART_ITEM = "EMPTY_CART_ITEM"
export const CART_SAVE_ADDRESS = "CART_SAVE_ADDRESS"
export const REMOVE_SAVED_ADDRESS = "REMOVE_SAVED_ADDRESS"
export const CART_SELECT_ADDRESS = "CART_SELECT_ADDRESS"
export const CART_SAVE_PAYMENT_METHOD = 'CART_SAVE_PAYMENT_METHOD';