export const SERVICES_LIST_REQUEST = "SERVICES_LIST_REQUEST"
export const SERVICES_LIST_SUCCESS = "SERVICES_LIST_SUCCESS"
export const SERVICES_LIST_FAIL = "SERVICES_LIST_FAIL"

export const SERVICES_DETAILS_REQUEST = "SERVICES_DETAILS_REQUEST"
export const SERVICES_DETAILS_SUCCESS = "SERVICES_DETAILS_SUCCESS"
export const SERVICES_DETAILS_FAIL = "SERVICES_DETAILS_FAIL"